/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyCategory } from '../../models/company-category';
import { CreateCompanyCategoryDto } from '../../models/create-company-category-dto';

export interface CompanyCategoriesControllerCreate$Params {
      body: CreateCompanyCategoryDto
}

export function companyCategoriesControllerCreate(http: HttpClient, rootUrl: string, params: CompanyCategoriesControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyCategory>> {
  const rb = new RequestBuilder(rootUrl, companyCategoriesControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyCategory>;
    })
  );
}

companyCategoriesControllerCreate.PATH = '/company-categories';
