/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BooleanFilterEnum } from '../../models/boolean-filter-enum';
import { DateFilterEnum } from '../../models/date-filter-enum';
import { NumberFilterEnum } from '../../models/number-filter-enum';
import { OrderEnum } from '../../models/order-enum';
import { StringFilterEnum } from '../../models/string-filter-enum';

export interface CompaniesControllerFindAll$Params {

/**
 * **Категория**
 */
  'category.name'?: string;

/**
 * Фильтр
 */
  'category.name-filter'?: StringFilterEnum;

/**
 * Порядок сортировки
 */
  'category.name-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'category.name-orderPlace'?: number;

/**
 * **Идентификатор категории**
 */
  categoryId?: string;

/**
 * Фильтр
 */
  'categoryId-filter'?: NumberFilterEnum;

/**
 * Порядок сортировки
 */
  'categoryId-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'categoryId-orderPlace'?: number;

/**
 * **Дата создания**
 */
  createdAt?: string;

/**
 * Фильтр
 */
  'createdAt-filter'?: DateFilterEnum;

/**
 * Порядок сортировки
 */
  'createdAt-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'createdAt-orderPlace'?: number;

/**
 * **Адреса электронных почт**
 */
  emails?: string;

/**
 * Фильтр
 */
  'emails-filter'?: StringFilterEnum;

/**
 * Порядок сортировки
 */
  'emails-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'emails-orderPlace'?: number;

/**
 * **Идентификатор**
 */
  id?: string;

/**
 * Фильтр
 */
  'id-filter'?: NumberFilterEnum;

/**
 * Порядок сортировки
 */
  'id-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'id-orderPlace'?: number;

/**
 * **Активная**
 */
  isActive?: BooleanFilterEnum;

/**
 * Порядок сортировки
 */
  'isActive-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'isActive-orderPlace'?: number;

/**
 * **Фамилия менеджера**
 */
  'manager.name.last'?: string;

/**
 * Фильтр
 */
  'manager.name.last-filter'?: StringFilterEnum;

/**
 * Порядок сортировки
 */
  'manager.name.last-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'manager.name.last-orderPlace'?: number;

/**
 * **Идентификатор менеджера**
 */
  managerId?: string;

/**
 * Фильтр
 */
  'managerId-filter'?: NumberFilterEnum;

/**
 * Порядок сортировки
 */
  'managerId-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'managerId-orderPlace'?: number;

/**
 * **Название компании**
 */
  name?: string;

/**
 * Фильтр
 */
  'name-filter'?: StringFilterEnum;

/**
 * Порядок сортировки
 */
  'name-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'name-orderPlace'?: number;

/**
 * **Телефоны**
 */
  phones?: string;

/**
 * Фильтр
 */
  'phones-filter'?: StringFilterEnum;

/**
 * Порядок сортировки
 */
  'phones-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'phones-orderPlace'?: number;

/**
 * **Дата обновления**
 */
  updatedAt?: string;

/**
 * Фильтр
 */
  'updatedAt-filter'?: DateFilterEnum;

/**
 * Порядок сортировки
 */
  'updatedAt-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'updatedAt-orderPlace'?: number;

/**
 * **Ссылки**
 */
  urls?: string;

/**
 * Фильтр
 */
  'urls-filter'?: StringFilterEnum;

/**
 * Порядок сортировки
 */
  'urls-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'urls-orderPlace'?: number;

/**
 * **Время работы**
 */
  workTime?: string;

/**
 * Фильтр
 */
  'workTime-filter'?: StringFilterEnum;

/**
 * Порядок сортировки
 */
  'workTime-order'?: OrderEnum;

/**
 * Приоритет сортировки  
 * *Чем меньше, тем приоритетнее*
 */
  'workTime-orderPlace'?: number;

/**
 * **Смещение**  
 * *Без заданного ограничения работать не будет*
 */
  offset?: number;

/**
 * **Ограничение**
 */
  limit?: number;
}

export function companiesControllerFindAll(http: HttpClient, rootUrl: string, params?: CompaniesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
  const rb = new RequestBuilder(rootUrl, companiesControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('category.name', params['category.name'], {"explode":false});
    rb.query('category.name-filter', params['category.name-filter'], {"explode":false});
    rb.query('category.name-order', params['category.name-order'], {"explode":false});
    rb.query('category.name-orderPlace', params['category.name-orderPlace'], {});
    rb.query('categoryId', params.categoryId, {"explode":false});
    rb.query('categoryId-filter', params['categoryId-filter'], {"explode":false});
    rb.query('categoryId-order', params['categoryId-order'], {"explode":false});
    rb.query('categoryId-orderPlace', params['categoryId-orderPlace'], {});
    rb.query('createdAt', params.createdAt, {"explode":false});
    rb.query('createdAt-filter', params['createdAt-filter'], {"explode":false});
    rb.query('createdAt-order', params['createdAt-order'], {"explode":false});
    rb.query('createdAt-orderPlace', params['createdAt-orderPlace'], {});
    rb.query('emails', params.emails, {"explode":false});
    rb.query('emails-filter', params['emails-filter'], {"explode":false});
    rb.query('emails-order', params['emails-order'], {"explode":false});
    rb.query('emails-orderPlace', params['emails-orderPlace'], {});
    rb.query('id', params.id, {"explode":false});
    rb.query('id-filter', params['id-filter'], {"explode":false});
    rb.query('id-order', params['id-order'], {"explode":false});
    rb.query('id-orderPlace', params['id-orderPlace'], {});
    rb.query('isActive', params.isActive, {"explode":false});
    rb.query('isActive-order', params['isActive-order'], {"explode":false});
    rb.query('isActive-orderPlace', params['isActive-orderPlace'], {});
    rb.query('manager.name.last', params['manager.name.last'], {"explode":false});
    rb.query('manager.name.last-filter', params['manager.name.last-filter'], {"explode":false});
    rb.query('manager.name.last-order', params['manager.name.last-order'], {"explode":false});
    rb.query('manager.name.last-orderPlace', params['manager.name.last-orderPlace'], {});
    rb.query('managerId', params.managerId, {"explode":false});
    rb.query('managerId-filter', params['managerId-filter'], {"explode":false});
    rb.query('managerId-order', params['managerId-order'], {"explode":false});
    rb.query('managerId-orderPlace', params['managerId-orderPlace'], {});
    rb.query('name', params.name, {"explode":false});
    rb.query('name-filter', params['name-filter'], {"explode":false});
    rb.query('name-order', params['name-order'], {"explode":false});
    rb.query('name-orderPlace', params['name-orderPlace'], {});
    rb.query('phones', params.phones, {"explode":false});
    rb.query('phones-filter', params['phones-filter'], {"explode":false});
    rb.query('phones-order', params['phones-order'], {"explode":false});
    rb.query('phones-orderPlace', params['phones-orderPlace'], {});
    rb.query('updatedAt', params.updatedAt, {"explode":false});
    rb.query('updatedAt-filter', params['updatedAt-filter'], {"explode":false});
    rb.query('updatedAt-order', params['updatedAt-order'], {"explode":false});
    rb.query('updatedAt-orderPlace', params['updatedAt-orderPlace'], {});
    rb.query('urls', params.urls, {"explode":false});
    rb.query('urls-filter', params['urls-filter'], {"explode":false});
    rb.query('urls-order', params['urls-order'], {"explode":false});
    rb.query('urls-orderPlace', params['urls-orderPlace'], {});
    rb.query('workTime', params.workTime, {"explode":false});
    rb.query('workTime-filter', params['workTime-filter'], {"explode":false});
    rb.query('workTime-order', params['workTime-order'], {"explode":false});
    rb.query('workTime-orderPlace', params['workTime-orderPlace'], {});
    rb.query('offset', params.offset, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<any>>;
    })
  );
}

companiesControllerFindAll.PATH = '/companies';
