/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateManagerDto } from '../../models/create-manager-dto';
import { Manager } from '../../models/manager';

export interface ManagersControllerCreate$Params {
      body: CreateManagerDto
}

export function managersControllerCreate(http: HttpClient, rootUrl: string, params: ManagersControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<Manager>> {
  const rb = new RequestBuilder(rootUrl, managersControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Manager>;
    })
  );
}

managersControllerCreate.PATH = '/managers';
