/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { RootService } from './services/root.service';
export { CompaniesService } from './services/companies.service';
export { CompanyCategoriesService } from './services/company-categories.service';
export { ContactFacePositionsService } from './services/contact-face-positions.service';
export { ContactFacesService } from './services/contact-faces.service';
export { ContactOffersService } from './services/contact-offers.service';
export { ContactsService } from './services/contacts.service';
export { ManagersService } from './services/managers.service';
