/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FindNamesResultDto } from '../../models/find-names-result-dto';

export interface ContactOffersControllerFindNames$Params {
}

export function contactOffersControllerFindNames(http: HttpClient, rootUrl: string, params?: ContactOffersControllerFindNames$Params, context?: HttpContext): Observable<StrictHttpResponse<FindNamesResultDto>> {
  const rb = new RequestBuilder(rootUrl, contactOffersControllerFindNames.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FindNamesResultDto>;
    })
  );
}

contactOffersControllerFindNames.PATH = '/contact-offers/names';
