/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContactOffer } from '../../models/contact-offer';
import { CreateContactOfferDto } from '../../models/create-contact-offer-dto';

export interface ContactOffersControllerCreate$Params {
      body: CreateContactOfferDto
}

export function contactOffersControllerCreate(http: HttpClient, rootUrl: string, params: ContactOffersControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactOffer>> {
  const rb = new RequestBuilder(rootUrl, contactOffersControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContactOffer>;
    })
  );
}

contactOffersControllerCreate.PATH = '/contact-offers';
