/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateContactOfferDto } from '../../models/update-contact-offer-dto';
import { UpdateResultDto } from '../../models/update-result-dto';

export interface ContactOffersControllerUpdate$Params {

/**
 * Идентификатор
 */
  id: number;
      body: UpdateContactOfferDto
}

export function contactOffersControllerUpdate(http: HttpClient, rootUrl: string, params: ContactOffersControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<UpdateResultDto>> {
  const rb = new RequestBuilder(rootUrl, contactOffersControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UpdateResultDto>;
    })
  );
}

contactOffersControllerUpdate.PATH = '/contact-offers/{id}';
