/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { appControllerGetApiInfo } from '../fn/root/app-controller-get-api-info';
import { AppControllerGetApiInfo$Params } from '../fn/root/app-controller-get-api-info';

@Injectable({ providedIn: 'root' })
export class RootService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `appControllerGetApiInfo()` */
  static readonly AppControllerGetApiInfoPath = '/';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appControllerGetApiInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  appControllerGetApiInfo$Response(params?: AppControllerGetApiInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return appControllerGetApiInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appControllerGetApiInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appControllerGetApiInfo(params?: AppControllerGetApiInfo$Params, context?: HttpContext): Observable<string> {
    return this.appControllerGetApiInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
