/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyCategory } from '../models/company-category';
import { Manager } from '../models/manager';
export interface Company {

  /**
   * Категория
   */
  category?: CompanyCategory;

  /**
   * Идентификатор категории
   */
  categoryId?: number | null;

  /**
   * Дата создания
   */
  createdAt: string;

  /**
   * Адреса электронных почт
   */
  emails?: string;

  /**
   * Сфера деятельности
   */
  fieldOfActivity?: string;

  /**
   * Идентификатор
   */
  id: number;

  /**
   * Активная
   */
  isActive?: boolean;

  /**
   * Менеджер
   */
  manager?: Manager;

  /**
   * Идентификатор менеджера
   */
  managerId?: number | null;

  /**
   * Название компании
   */
  name: string;

  /**
   * Примечания
   */
  notes?: string;

  /**
   * Расположение офиса
   */
  officeAddress?: string;

  /**
   * Телефоны
   */
  phones?: string;

  /**
   * Почтовый адрес
   */
  postalAddress?: string;

  /**
   * Издания
   */
  publications?: string;

  /**
   * Дата изменения
   */
  updatedAt: string;

  /**
   * Ссылки
   */
  urls?: string;

  /**
   * Время работы
   */
  workTime?: string;
}
