/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyCategory {

  /**
   * Дата создания
   */
  createdAt: string;

  /**
   * Идентификатор
   */
  id: number;

  /**
   * Активная
   */
  isActive?: boolean;

  /**
   * Название категории
   */
  name: string;

  /**
   * Дата изменения
   */
  updatedAt: string;
}
