/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactOffer {

  /**
   * Идентификатор
   */
  id: number;

  /**
   * Активная
   */
  isActive?: boolean;

  /**
   * Название предложения
   */
  name: string;
}
