/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Company } from '../models/company';
import { ContactFace } from '../models/contact-face';
import { ContactFacePosition } from '../models/contact-face-position';
import { Manager } from '../models/manager';
export interface Contact {

  /**
   * Компания
   */
  company: Company;

  /**
   * Идентификатор компании
   */
  companyId: number;

  /**
   * Дата контакта
   */
  contactDate?: string;

  /**
   * Контактное лицо
   */
  contactFace?: ContactFace;

  /**
   * Идентификатор контактного лица
   */
  contactFaceId?: number | null;

  /**
   * Дата создания
   */
  createdAt: string;

  /**
   * Описание
   */
  description?: string;

  /**
   * Адреса электронных почт
   */
  emails?: string;

  /**
   * Идентификатор
   */
  id: number;

  /**
   * Активная
   */
  isActive?: boolean;

  /**
   * Менеджер
   */
  manager?: Manager;

  /**
   * Идентификатор менеджера
   */
  managerId?: number | null;

  /**
   * Дата следующего контакта
   */
  nextContactDate?: string;

  /**
   * Примечания по контактному лицу
   */
  notesOnContactFace?: string;

  /**
   * Предложение
   */
  offer?: ContactFacePosition;

  /**
   * Контактные телефоны
   */
  phones?: string;

  /**
   * Состояние
   */
  status: 'CANCELED' | 'COMPLETED' | 'PLANNING';

  /**
   * Дата изменения
   */
  updatedAt: string;
}
