/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ContactStatusEnum {
  Canceled = 'CANCELED',
  Completed = 'COMPLETED',
  Planning = 'PLANNING'
}
