/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContactFacePosition } from '../models/contact-face-position';
export interface CreateContactDto {

  /**
   * Идентификатор компании
   */
  companyId: number;

  /**
   * Дата контакта
   */
  contactDate?: string;

  /**
   * Идентификатор контактного лица
   */
  contactFaceId?: number | null;

  /**
   * Описание
   */
  description?: string;

  /**
   * Адреса электронных почт
   */
  emails?: string;

  /**
   * Активная
   */
  isActive?: boolean;

  /**
   * Идентификатор менеджера
   */
  managerId?: number | null;

  /**
   * Дата следующего контакта
   */
  nextContactDate?: string;

  /**
   * Примечания по контактному лицу
   */
  notesOnContactFace?: string;

  /**
   * Предложение
   */
  offer?: ContactFacePosition;

  /**
   * Контактные телефоны
   */
  phones?: string;

  /**
   * Состояние
   */
  status: 'CANCELED' | 'COMPLETED' | 'PLANNING';
}
