/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Company } from '../models/company';
import { Name } from '../models/name';
export interface CreateContactFaceDto {

  /**
   * Компания
   */
  company: Company;

  /**
   * Идентификатор компании
   */
  companyId: number;

  /**
   * Адрес электронной почты
   */
  email?: string;

  /**
   * Активная
   */
  isActive?: boolean;

  /**
   * ФИО
   */
  name: Name;

  /**
   * Заметки
   */
  notes?: string;

  /**
   * Телефон
   */
  phone?: string;

  /**
   * Идентификатор должности
   */
  positionId?: number | null;
}
