/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateContactFacePositionDto {

  /**
   * Активная
   */
  isActive?: boolean;

  /**
   * Название должности
   */
  name: string;
}
