/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum DateFilterEnum {
  Between = 'BETWEEN',
  Equals = 'EQUALS',
  In = 'IN',
  LessThan = 'LESS_THAN',
  LessThanOrEqual = 'LESS_THAN_OR_EQUAL',
  MoreThan = 'MORE_THAN',
  MoreThanOrEqual = 'MORE_THAN_OR_EQUAL',
  NotEquals = 'NOT_EQUALS',
  StartsWith = 'STARTS_WITH'
}
