/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Contact } from '../models/contact';
export interface FindAllContactsDto {
  count: number;
  items: Array<Contact>;
}
