/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContactOffer } from '../models/contact-offer';
export interface FindAllContactOffersDto {
  count: number;
  items: Array<ContactOffer>;
}
