/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContactFacePosition } from '../models/contact-face-position';
export interface FindAllContactFacePositionsDto {
  count: number;
  items: Array<ContactFacePosition>;
}
