/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Manager } from '../models/manager';
export interface FindAllManagersDto {
  count: number;
  items: Array<Manager>;
}
