/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContactFace } from '../models/contact-face';
export interface FindAllContactFacesDto {
  count: number;
  items: Array<ContactFace>;
}
