/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyCategory } from '../models/company-category';
export interface FindAllCompanyCategoriesDto {
  count: number;
  items: Array<CompanyCategory>;
}
