/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Company } from '../models/company';
export interface FindAllCompaniesDto {
  count: number;
  items: Array<Company>;
}
