/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Name {

  /**
   * Имя
   */
  first: string;

  /**
   * Фамилия
   */
  last: string;

  /**
   * Отчество
   */
  middle?: string;
}
