/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCompanyDto {

  /**
   * Идентификатор категории
   */
  categoryId?: number | null;

  /**
   * Адреса электронных почт
   */
  emails?: string;

  /**
   * Сфера деятельности
   */
  fieldOfActivity?: string;

  /**
   * Активная
   */
  isActive?: boolean;

  /**
   * Идентификатор менеджера
   */
  managerId?: number | null;

  /**
   * Название компании
   */
  name?: string;

  /**
   * Примечания
   */
  notes?: string;

  /**
   * Расположение офиса
   */
  officeAddress?: string;

  /**
   * Телефоны
   */
  phones?: string;

  /**
   * Почтовый адрес
   */
  postalAddress?: string;

  /**
   * Издания
   */
  publications?: string;

  /**
   * Ссылки
   */
  urls?: string;

  /**
   * Время работы
   */
  workTime?: string;
}
