/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateContactOfferDto {

  /**
   * Активная
   */
  isActive?: boolean;

  /**
   * Название предложения
   */
  name?: string;
}
