/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContactFace } from '../../models/contact-face';

export interface ContactFacesControllerFindOne$Params {

/**
 * Идентификатор
 */
  id: number;
}

export function contactFacesControllerFindOne(http: HttpClient, rootUrl: string, params: ContactFacesControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactFace>> {
  const rb = new RequestBuilder(rootUrl, contactFacesControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContactFace>;
    })
  );
}

contactFacesControllerFindOne.PATH = '/contact-faces/{id}';
