/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContactFace } from '../../models/contact-face';
import { UpdateContactFaceDto } from '../../models/update-contact-face-dto';

export interface ContactFacesControllerUpdate$Params {

/**
 * Идентификатор
 */
  id: number;
      body: UpdateContactFaceDto
}

export function contactFacesControllerUpdate(http: HttpClient, rootUrl: string, params: ContactFacesControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactFace>> {
  const rb = new RequestBuilder(rootUrl, contactFacesControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContactFace>;
    })
  );
}

contactFacesControllerUpdate.PATH = '/contact-faces/{id}';
