/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContactFace } from '../../models/contact-face';
import { CreateContactFaceDto } from '../../models/create-contact-face-dto';

export interface ContactFacesControllerCreate$Params {
      body: CreateContactFaceDto
}

export function contactFacesControllerCreate(http: HttpClient, rootUrl: string, params: ContactFacesControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactFace>> {
  const rb = new RequestBuilder(rootUrl, contactFacesControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContactFace>;
    })
  );
}

contactFacesControllerCreate.PATH = '/contact-faces';
