/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FindUserNamesResultDto } from '../../models/find-user-names-result-dto';

export interface ContactFacesControllerFindNames$Params {
}

export function contactFacesControllerFindNames(http: HttpClient, rootUrl: string, params?: ContactFacesControllerFindNames$Params, context?: HttpContext): Observable<StrictHttpResponse<FindUserNamesResultDto>> {
  const rb = new RequestBuilder(rootUrl, contactFacesControllerFindNames.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FindUserNamesResultDto>;
    })
  );
}

contactFacesControllerFindNames.PATH = '/contact-faces/names';
